# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fancy"

# Light sources settings.
[light_sources]
	# Enable entities light source.
	entities = true
	# Enable first-person player light source.
	self = true
	# Enable block entities light source.
	block_entities = true
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "off"

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				glow_item_frame = false
				player = true
				item = true
				rabbit = true
				endermite = true
				arrow = true
				warden = true
				ender_pearl = true
				area_effect_cloud = true
				zombie = true
				experience_orb = true
				wither_skeleton = true
				pillager = true
				villager = true
				enderman = true
				ravager = true
				zombie_villager = true
				creeper = true
				iron_golem = true
				polar_bear = true
				slime = true
				trident = true
				blaze = true
				small_fireball = true
				spider = true
				ender_dragon = true
				lightning_bolt = true
				firework_rocket = true
				phantom = true
				potion = true
				shulker = true
				item_frame = true
				vindicator = true
				husk = true
				chicken = true
				mule = true
				tnt_minecart = true
				wandering_trader = true
				cave_spider = true
				skeleton = true
				armor_stand = true
				glow_squid = true
				cow = true
				salmon = true
				bat = true
				squid = true
				cod = true
				bee = true
				chest_minecart = true
				egg = true
				snowball = true
				allay = true
				axolotl = true
				boat = true
				chest_boat = true
				cat = true
				camel = true
				dolphin = true
				donkey = true
				dragon_fireball = true
				drowned = true
				elder_guardian = true
				end_crystal = true
				evoker = true
				evoker_fangs = true
				eye_of_ender = true
				falling_block = true
				fox = true
				frog = true
				ghast = true
				giant = true
				goat = true
				guardian = true
				hoglin = true
				horse = true
				illusioner = true
				fireball = true
				leash_knot = true
				llama = true
				llama_spit = true
				magma_cube = true
				marker = true
				minecart = true
				command_block_minecart = true
				furnace_minecart = true
				hopper_minecart = true
				spawner_minecart = true
				mooshroom = true
				ocelot = true
				painting = true
				panda = true
				parrot = true
				pig = true
				piglin = true
				piglin_brute = true
				tnt = true
				pufferfish = true
				experience_bottle = true
				fishing_bobber = true
				silverfish = true
				shulker_bullet = true
				vex = true
				spectral_arrow = true
				wolf = true

			[light_sources.settings.entities.armourers_workshop]
				mannequin = true
				seat = true

			[light_sources.settings.entities.sculk_worm]
				sculk_worm_entity = true
				sculk_segment_entity = true
				sonic_grenade_entity = true
				sculk_watcher_entity = true
				infected_zombie_entity = true
				unstable_enderman_entity = true
				infected_bat_entity = true
				infected_creeper_entity = true
				infected_spawn_entity = true
				infector_spider_entity = true
				infected_skeleton_entity = true

